apache/skywalking-booster-ui

.gitignore, README.md, package-lock.json, package.json
Optimize docs and upgrade packages.
=> build: optimize docs and upgrade packages

.github/workflows/nodejs.yml, package-lock.json, package.json, postcss.config.js, src/assets/img/icons.js, src/styles/lib.scss, stylelint.config.js
Add git hooks to automatically format the uniform code style.
=> build: add git hooks for code style

src/components/DateCalendar.vue, src/components/TimePicker.vue
Fix DateTimePicker component for selecting time range.
Signed-off-by: QIuxia Fan <qiuxiafan@apache.org>
=> fix: update DateTimePicker

src/components/Icon.vue, src/locales/lang/en.ts, src/locales/lang/zh.ts, src/router/index.ts, src/store/modules/dashboard.ts, src/types/dashboard.ts, src/views/dashboard/Edit.vue, src/views/dashboard/controls/Tab.vue, src/views/dashboard/controls/Widget.vue, src/views/dashboard/data.ts, src/views/dashboard/panel/Layout.vue, src/views/dashboard/panel/Tool.vue, src/views/dashboard/related/profile/Content.vue, src/views/dashboard/related/profile/components/SpanTree.vue, src/views/dashboard/related/trace/components/Table/TableItem.vue
Implement adding controls in Tabs.
Video
https://user-images.githubusercontent.com/20871783/156704888-cb65483f-856e-4bfc-b76f-65e66aa19fe9.mov
=> feat: Implement adding controls in Tabs

src/components/Icon.vue, src/hooks/useDashboardsSession.ts, src/layout/Index.vue, src/layout/components/SideBar.vue, src/locales/lang/en.ts, src/locales/lang/zh.ts, src/store/modules/dashboard.ts, src/views/Layer.vue, src/views/dashboard/Edit.vue, src/views/dashboard/List.vue, src/views/dashboard/controls/Log.vue, src/views/dashboard/controls/Profile.vue, src/views/dashboard/controls/Tab.vue, src/views/dashboard/controls/Topology.vue, src/views/dashboard/controls/Trace.vue, src/views/dashboard/controls/Widget.vue, src/views/dashboard/graphs/EndpointList.vue, src/views/dashboard/graphs/InstanceList.vue, src/views/dashboard/graphs/ServiceList.vue, src/views/dashboard/panel/Tool.vue, src/views/dashboard/related/topology/components/Graph.vue, src/views/dashboard/related/topology/components/PodTopology.vue, src/views/dashboard/related/topology/components/Settings.vue
Add switch to control dashboard mode.
Reset current dashboard.
Video
https://user-images.githubusercontent.com/20871783/159250276-3d646544-f234-4ddd-ada7-22e38ea5471c.mov
=> feat: add switch to control dashboard mode

src/locales/lang/zh.ts, src/router/infrastructure.ts, src/store/modules/topology.ts, src/views/dashboard/List.vue, src/views/dashboard/configuration/widget/MetricOptions.vue, src/views/dashboard/graphs/EndpointList.vue, src/views/dashboard/graphs/InstanceList.vue, src/views/dashboard/related/topology/Index.vue, src/views/dashboard/related/topology/components/Graph.vue, src/views/dashboard/related/topology/components/PodTopology.vue, src/views/dashboard/related/topology/components/Sankey.vue, src/views/dashboard/related/topology/components/Settings.vue
Save and init topology templates.
video
https://user-images.githubusercontent.com/20871783/159411936-45274bd9-4ec2-4d52-87f6-379220e17909.mov
=> feat: save and init topology templates

src/locales/lang/en.ts, src/locales/lang/zh.ts, src/router/database.ts, src/store/modules/dashboard.ts, src/views/dashboard/Edit.vue, src/views/dashboard/List.vue, src/views/dashboard/New.vue, src/views/dashboard/configuration/Widget.vue, src/views/dashboard/controls/Widget.vue, src/views/dashboard/data.ts, src/views/dashboard/graphs/EndpointList.vue, src/views/dashboard/graphs/InstanceList.vue, src/views/dashboard/graphs/ServiceList.vue, src/views/dashboard/panel/Tool.vue, src/views/dashboard/related/topology/components/Graph.vue, src/views/dashboard/related/topology/components/PodTopology.vue
Update dashboard list, reload templates and bugs fix.
Video
https://user-images.githubusercontent.com/20871783/159475919-cbce57e0-6cdc-49db-9d3c-b1e215a65496.mov
=> feat: update dashboard list and reload templates

src/router/infrastructure.ts, src/store/modules/dashboard.ts, src/views/Layer.vue, src/views/dashboard/Edit.vue, src/views/dashboard/graphs/EndpointList.vue, src/views/dashboard/graphs/InstanceList.vue, src/views/dashboard/graphs/ServiceList.vue, src/views/dashboard/panel/Layout.vue, src/views/dashboard/panel/Tool.vue, src/views/dashboard/related/topology/components/Graph.vue
Reset current dashboard due to pages forwarding.
Video
https://user-images.githubusercontent.com/20871783/159628512-5344c99f-03d4-4d73-bee5-ff03a671a317.mov
=> fix: reset current dashboard due to pages forwarding

src/hooks/useProcessor.ts, src/store/modules/dashboard.ts, src/store/modules/selectors.ts, src/views/dashboard/List.vue, src/views/dashboard/configuration/widget/MetricOptions.vue, src/views/dashboard/configuration/widget/StandardOptions.vue, src/views/dashboard/controls/Widget.vue, src/views/dashboard/graphs/EndpointList.vue, src/views/dashboard/graphs/InstanceList.vue, src/views/dashboard/graphs/Table.vue, src/views/dashboard/panel/Tool.vue
Update components, sort dashboards, fix saving templates.
Video
https://user-images.githubusercontent.com/20871783/159681645-bdcacc0e-947d-411c-81c0-60b116179eee.mov
Signed-off-by:  Qiuxia Fan <qiuxiafan@apache.org>
=> fix: update components, save templates

src/locales/lang/en.ts, src/locales/lang/zh.ts, src/store/data.ts, src/store/modules/dashboard.ts, src/types/dashboard.ts, src/views/Layer.vue, src/views/dashboard/Edit.vue, src/views/dashboard/configuration/Text.vue, src/views/dashboard/configuration/Widget.vue, src/views/dashboard/configuration/index.ts, src/views/dashboard/controls/Tab.vue, src/views/dashboard/controls/Text.vue, src/views/dashboard/data.ts, src/views/dashboard/panel/Layout.vue, src/views/dashboard/panel/Tool.vue, src/views/dashboard/related/topology/components/Graph.vue, src/views/dashboard/related/topology/components/PodTopology.vue, src/views/dashboard/related/topology/components/Settings.vue, src/views/dashboard/related/trace/utils/d3-trace-list.ts
Implement Text control and update Topology.
Video 
https://user-images.githubusercontent.com/20871783/160076537-a2440cd7-a49b-49d5-9255-f5c12e9ae40b.mov
=> feat: Implement Text control and update Topology

src/hooks/useProcessor.ts, src/views/dashboard/configuration/widget/metric/Index.vue, src/views/dashboard/controls/Widget.vue, src/views/dashboard/related/topology/components/Metrics.vue
Set different scope for topN metrics.
Video 
https://user-images.githubusercontent.com/20871783/160269449-ca38d184-17b0-4c78-a001-4bde820b189d.mov
=> fix: set different scope for topN metrics

src/store/modules/dashboard.ts, src/views/dashboard/configuration/Widget.vue, src/views/dashboard/configuration/widget/metric/Index.vue, src/views/dashboard/configuration/widget/metric/Standard.vue, src/views/dashboard/controls/Widget.vue, src/views/dashboard/data.ts
Fix calculating widget index and initing metrics config.
Video
https://user-images.githubusercontent.com/20871783/160289090-051fb02f-9a1b-42a1-9445-5235d7a62f10.mov
https://user-images.githubusercontent.com/20871783/160289194-3319acb3-37c1-4db9-b5ab-4570944f86d0.mov
=> fix: calculate widget index and init metrics config

src/hooks/useProcessor.ts, src/store/modules/dashboard.ts, src/store/modules/topology.ts, src/types/dashboard.ts, src/views/dashboard/configuration/Widget.vue, src/views/dashboard/configuration/widget/graph-styles/TopList.vue, src/views/dashboard/configuration/widget/metric/Index.vue, src/views/dashboard/configuration/widget/metric/Standard.vue, src/views/dashboard/data.ts, src/views/dashboard/graphs/EndpointList.vue, src/views/dashboard/graphs/InstanceList.vue, src/views/dashboard/graphs/ServiceList.vue, src/views/dashboard/graphs/TopList.vue, src/views/dashboard/related/topology/components/Graph.vue, src/views/dashboard/related/topology/components/Settings.vue, src/views/dashboard/related/topology/utils/legend.ts, src/views/dashboard/related/topology/utils/nodeElement.ts
Update pagination for service list, endpoint list, instance list. Add legend configs. Fixes sort order
Video 
https://user-images.githubusercontent.com/20871783/160597843-c584b5ef-cde9-4177-a6c7-edd3003a32ab.mov
=> fix: update pagination for service list, endpoint list, instance list and add legend configs

src/assets/icons/control.svg, src/hooks/useProcessor.ts, src/styles/reset.scss, src/views/dashboard/configuration/Widget.vue, src/views/dashboard/configuration/widget/WidgetOptions.vue, src/views/dashboard/configuration/widget/metric/Standard.vue, src/views/dashboard/data.ts, src/views/dashboard/graphs/Card.vue, src/views/dashboard/graphs/EndpointList.vue, src/views/dashboard/graphs/InstanceList.vue, src/views/dashboard/graphs/Line.vue, src/views/dashboard/graphs/ServiceList.vue, src/views/dashboard/panel/Tool.vue
Update tooltips and controls.
video 
https://user-images.githubusercontent.com/20871783/161048704-7d56dc23-bc2e-4e2e-b8b0-461d5a3297b3.mov
=> fix: update tooltips and controls

src/layout/components/NavBar.vue, src/views/dashboard/configuration/Widget.vue, src/views/dashboard/configuration/widget/metric/Index.vue, src/views/dashboard/configuration/widget/metric/Standard.vue, src/views/dashboard/graphs/EndpointList.vue, src/views/dashboard/graphs/InstanceList.vue, src/views/dashboard/graphs/ServiceList.vue, src/views/dashboard/panel/Tool.vue
Update style and set labels
Video 
https://user-images.githubusercontent.com/20871783/161199988-572c6f1d-1247-420c-944e-763ab03addd6.mov
=> fix: update style and set labels

src/components/Graph.vue, src/views/dashboard/configuration/Widget.vue, src/views/dashboard/graphs/EndpointList.vue, src/views/dashboard/graphs/InstanceList.vue, src/views/dashboard/panel/Tool.vue
Update selector params.
Video 
https://user-images.githubusercontent.com/20871783/161365507-cef46adf-7119-4822-95ca-191ccd73f6b0.mov
=> fix: update selector params and list graphs

src/components/Graph.vue, src/views/dashboard/related/topology/components/Graph.vue
Set graph style and topology node services.
Screenshot
=> fix: set graph style and topology node services

src/views/dashboard/controls/Text.vue
Fixes text control styles.
Video 
https://user-images.githubusercontent.com/20871783/161520995-82a9e114-d976-4f23-a8cc-94f0c87c31ef.mov
=> fix: update text control styles

package-lock.json, package.json, src/styles/reset.scss
=> build: update packages

src/views/Settings.vue, src/views/dashboard/panel/Layout.vue, src/views/dashboard/panel/Tool.vue
Close https://github.com/apache/skywalking/issues/8835
Video 
refresh
https://user-images.githubusercontent.com/20871783/162914699-a5c69238-32dc-48d5-993a-0771c3ae86f6.mov
auto refresh
https://user-images.githubusercontent.com/20871783/162914718-73d17fcb-0dbd-4462-be43-531089fabe99.mov
=> fix: refresh dashboards with current selectors

src/hooks/data.ts, src/hooks/useListConfig.ts, src/hooks/useProcessor.ts, src/views/dashboard/data.ts, src/views/dashboard/graphs/Card.vue
Add `Percentage + Avg` and `Apdex + Avg-preview`.
Video 
https://user-images.githubusercontent.com/20871783/163359151-c1885574-93c9-4abd-9dc3-ecac8263956b.mov
=> feat: add Avg calculations

src/views/dashboard/configuration/widget/metric/Index.vue
Fixes metrics index
Video 
https://user-images.githubusercontent.com/20871783/163513038-bc7115cc-8128-4113-aef4-cd9570442a5d.mov
=> fix: keep metrics index

package-lock.json, package.json, vue.config.js
Remove compression plugin and config.
=> build: remove compression plugin and config

src/store/modules/app.ts, src/views/Settings.vue
=> fix: set UTC when page loads

src/assets/icons/arrow-down.svg, src/views/dashboard/related/trace/Detail.vue, src/views/dashboard/related/trace/components/List.vue, src/views/dashboard/related/trace/utils/d3-trace-list.ts
optimize the trace widget style.
=> fix: optimize the trace widget

src/store/modules/ebpf.ts, src/store/modules/profile.ts, src/views/dashboard/related/profile/components/TaskList.vue
Verify query params to avoid invalid queries.
=> fix: verify query params to avoid invalid queries

src/components/Graph.vue, src/layout/components/SideBar.vue, src/views/dashboard/controls/Tab.vue, src/views/dashboard/panel/Tool.vue, src/views/dashboard/related/topology/components/PodTopology.vue
Fixes dropdown for the Tab widget, instance relation selectors and the sankey graph.
Video 
https://user-images.githubusercontent.com/20871783/167371190-7604e73d-5946-4fdc-93d2-14ef348dc280.mov
https://user-images.githubusercontent.com/20871783/167405013-bee858a4-1e01-4520-8a76-712674aafb77.mov
=> fix: set dropdown for the Tab widget, init instance relation selectors, update sankey graph

src/views/dashboard/configuration/widget/WidgetOptions.vue, src/views/dashboard/related/topology/components/Graph.vue, src/views/dashboard/related/topology/components/PodTopology.vue
Fixes graph options. Add user tips for topology links.
Video 
https://user-images.githubusercontent.com/20871783/167533774-f6d23b67-e068-4f5a-8747-6d396b6a08f8.mov
=> fix: set graph options 

src/graphql/fragments/ebpf.ts, src/types/ebpf.d.ts
Remove the layer filed from the Process.
=> feat: remove the layer filed from the Process

src/components/DateCalendar.vue, src/store/modules/ebpf.ts
Fixes date to 0 and removes duration filed.
Screenshot
=> fix: set date to 0 and remove duration filed

src/graphql/fragments/ebpf.ts, src/locales/lang/en.ts
=> fix: update schedules query

src/graphql/fragments/log.ts, src/graphql/fragments/selector.ts, src/graphql/fragments/trace.ts, src/graphql/query/log.ts, src/graphql/query/trace.ts, src/locales/lang/en.ts, src/locales/lang/zh.ts, src/store/modules/log.ts, src/store/modules/trace.ts, src/views/components/ConditionTags.vue, src/views/dashboard/related/log/Header.vue, src/views/dashboard/related/trace/Filter.vue, src/views/dashboard/related/trace/components/Table/TableItem.vue
Implement tags auto-complete for Trace and Log. Closes https://github.com/apache/skywalking/issues/8933
Video 
https://user-images.githubusercontent.com/20871783/168020109-8e2c4532-3b84-4ced-9c60-3f715367ac34.mov
=> feat: Implement tags auto-complete for Trace and Log

src/store/modules/ebpf.ts, src/views/components/ConditionTags.vue, src/views/dashboard/related/ebpf/components/EBPFStack.vue
Support multiple trees for the flame graph.
Video 
https://user-images.githubusercontent.com/20871783/168078763-53626a60-0aa1-4bd4-804f-adb6b010f76d.mov
=> feat: support multiple trees for the flame graph

src/App.vue, src/layout/components/SideBar.vue, src/views/dashboard/related/ebpf/components/EBPFStack.vue
Fixes the page doesn't need to be re-rendered when the url changes. Closes https://github.com/apache/skywalking/issues/9058
Video 
https://user-images.githubusercontent.com/20871783/168216927-e1c5af8c-a664-4fba-9d0b-ac540ce4efed.mov
=> fix: the page doesn't need to be re-rendered when the url changes

src/layout/components/AppMain.vue, src/layout/components/NavBar.vue, src/main.ts, src/store/modules/dashboard.ts, src/store/modules/ebpf.ts, src/store/modules/event.ts, src/store/modules/log.ts, src/store/modules/profile.ts, src/store/modules/selectors.ts, src/store/modules/trace.ts
Fixes duration time.
Video 
https://user-images.githubusercontent.com/20871783/168460602-b9898cf5-8b9b-4811-b8d6-386559742c86.mov
=> fix: set duration time

src/types/ebpf.d.ts, src/views/dashboard/related/ebpf/Content.vue, src/views/dashboard/related/ebpf/components/EBPFSchedules.vue, src/views/dashboard/related/ebpf/components/EBPFStack.vue, src/views/dashboard/related/ebpf/components/NewTask.vue
Polish the eBPF profiling widget.
Video 
https://user-images.githubusercontent.com/20871783/169006498-7d77c0cf-0b00-486a-a4d9-7785358c91ee.mov
=> fix: polish the eBPF profiling widget

package-lock.json, package.json, src/views/dashboard/related/ebpf/Content.vue, src/views/dashboard/related/ebpf/components/EBPFSchedules.vue
Remove a timeline graph from the eBPF profiling widget.
Screenshot
=> refactor: remove a timeline graph from the eBPF profiling widget

src/graphql/fragments/log.ts, src/graphql/fragments/trace.ts, src/store/modules/log.ts, src/store/modules/trace.ts, src/views/dashboard/related/components/LogTable/Index.vue, src/views/dashboard/related/log/Header.vue, src/views/dashboard/related/log/List.vue, src/views/dashboard/related/trace/Detail.vue, src/views/dashboard/related/trace/Filter.vue, src/views/dashboard/related/trace/TraceList.vue, src/views/dashboard/related/trace/components/D3Graph/SpanDetail.vue
Remove the total filed from query conditions.
Video
https://user-images.githubusercontent.com/20871783/169232937-24f32361-d0d3-437b-a47e-3f2b6d3bfc0d.mov
=> feat: remove the total filed from query conditions

src/graphql/fragments/alarm.ts, src/graphql/fragments/event.ts, src/graphql/fragments/log.ts, src/store/modules/event.ts, src/views/alarm/Header.vue, src/views/dashboard/related/log/Header.vue, src/views/event/Header.vue
Remove needTotal and total fields from query conditions
Video 
https://user-images.githubusercontent.com/20871783/169282739-478e7103-f553-454e-8b9b-c38137e2c064.mov
=> feat: remove needTotal and total fields from query conditions

src/constants/data.ts, src/layout/components/SideBar.vue, src/locales/index.ts, src/views/Settings.vue, src/views/dashboard/related/ebpf/components/EBPFStack.vue
Add a Spanish option in the lang selector. 
Fix the eBPF profiling widget when there is a large gap between the maximum and minimum values.
Video 
https://user-images.githubusercontent.com/20871783/169943693-680f3bfd-7397-46ad-9da1-dea1cd3ebdb6.mov
=> feat: add a Spanish option in the lang selector

src/store/modules/ebpf.ts, src/types/trace.d.ts, src/views/dashboard/graphs/TopList.vue, src/views/dashboard/graphs/components/ColumnGraph.vue, src/views/dashboard/related/ebpf/Content.vue, src/views/dashboard/related/ebpf/components/EBPFSchedules.vue, src/views/dashboard/related/ebpf/components/EBPFStack.vue, src/views/dashboard/related/profile/Content.vue, src/views/dashboard/related/trace/Detail.vue, src/views/dashboard/related/trace/components/D3Graph/Index.vue, src/views/dashboard/related/trace/components/D3Graph/SpanDetail.vue
Closes https://github.com/apache/skywalking/issues/9015. Also fixes eBPF profiling tooltips and the desc for topList graph.
Screenshots
=> feat: sort spans with `startTime` or `spanId` in a segment 

src/types/ebpf.d.ts, src/views/dashboard/related/ebpf/components/EBPFSchedules.vue, src/views/dashboard/related/ebpf/components/EBPFStack.vue
Add `Percentage Of Root` and `Percentage Of Selected` in the eBPF widget.
Screenshots
=> feat: add `Percentage Of Root` and `Percentage Of Selected` in the eBPF widget

src/locales/lang/en.ts, src/locales/lang/es.ts, src/router/alarm.ts, src/views/Alarm.vue, src/views/dashboard/related/log/Header.vue, src/views/dashboard/related/log/data.ts
Fixes query conditions for the browser logs. Reference https://github.com/apache/skywalking/discussions/9208
Screenshots
=> fix: update query conditions for the browser logs

src/store/modules/app.ts, src/views/Settings.vue
fix https://github.com/apache/skywalking/issues/9224
=> fix:clear interval fail when close autoRefresh

src/views/dashboard/controls/Ebpf.vue, src/views/dashboard/controls/Log.vue, src/views/dashboard/controls/Profile.vue, src/views/dashboard/controls/Trace.vue, src/views/dashboard/graphs/EndpointList.vue, src/views/dashboard/graphs/InstanceList.vue, src/views/dashboard/graphs/ServiceList.vue, src/views/dashboard/related/components/LogTable/Index.vue, src/views/dashboard/related/components/LogTable/LogBrowser.vue, src/views/dashboard/related/components/LogTable/LogDetail.vue, src/views/dashboard/related/ebpf/Header.vue, src/views/dashboard/related/log/Header.vue, src/views/dashboard/related/profile/Header.vue, src/views/dashboard/related/trace/Filter.vue
=> fix: optimize widgets

src/views/components/ConditionTags.vue
Fixes https://github.com/apache/skywalking/issues/9317
Screenshot
=> fix: set tags dropdown style

src/views/dashboard/related/topology/components/Graph.vue
Closes https://github.com/apache/skywalking/issues/9315
Video 
https://user-images.githubusercontent.com/20871783/178637503-84389641-2f47-4491-8169-0645d9b3163b.mov
=> fix: init legend metrics for topology

src/locales/lang/en.ts, src/locales/lang/es.ts, src/locales/lang/zh.ts, src/views/dashboard/configuration/widget/AssociateOptions.vue, src/views/dashboard/configuration/widget/WidgetOptions.vue, src/views/dashboard/related/topology/components/Sankey.vue
Fixes widget name rules and the association selector.
Video 
https://user-images.githubusercontent.com/20871783/178924901-99af3957-cdb0-403c-8cb4-af937d7cd917.mov
=> fix: update widget name rules and the association selector options

src/components/Graph.vue, src/views/dashboard/related/event/Content.vue
Support associations with the short time range.
Video 
https://user-images.githubusercontent.com/20871783/179662730-2b37552f-3442-4d8a-8851-3ea4a2c82ff4.mov
=> fix: support associations with the short time range

src/components/Graph.vue, src/views/dashboard/related/event/Content.vue
Fixes event associations with the duration step.
Video
https://user-images.githubusercontent.com/20871783/179677050-06e01c72-818c-430f-9db7-4365aa49f0ac.mov
Signed-off-by: QIuxia Fan <qiuxiafan@apache.org>
=> fix: update event associations with the duration step

src/components/Graph.vue, src/views/dashboard/related/event/Content.vue
Fixes https://github.com/apache/skywalking/issues/9362
Screenshot
=> fix: update event widget

src/views/components/ConditionTags.vue
Refactor the tags component for searching tag keys or values.
Video 
https://user-images.githubusercontent.com/20871783/180742079-1c38076e-f431-4992-8430-feaf11f7bec5.mov
=> refactor: update the tags component 

src/views/dashboard/related/log/LogTable/LogService.vue
Fixes the log details don't display when the log fields don't have value
Video 
https://user-images.githubusercontent.com/20871783/181235020-6c958b8d-cce6-49cc-85ea-7ab4e16ee895.mov
=> fix:  the log details don't display when the log fields don't have value

src/assets/icons/keyboard_arrow_down.svg, src/assets/icons/keyboard_arrow_up.svg, src/components/Graph.vue, src/store/modules/log.ts, src/store/modules/trace.ts, src/views/dashboard/related/event/Content.vue, src/views/dashboard/related/log/Header.vue, src/views/dashboard/related/trace/Filter.vue
Event widget associates with trace and log widget.
Video 
https://user-images.githubusercontent.com/20871783/181707389-a4803b7e-6f8d-44d6-825c-58edb185b6b9.mov
=> feat: event widget associates with trace and log widget

src/views/dashboard/related/trace/Filter.vue
Fixes query order for trace list.
Video 
https://user-images.githubusercontent.com/20871783/183040924-837ff1ad-3dd5-471a-b34f-562c7ecf7b6c.mov
=> fix: update query order for trace list

src/hooks/data.ts, src/hooks/useProcessor.ts, src/views/dashboard/data.ts
According to https://github.com/apache/skywalking/pull/9432#discussion_r939750594, add a calculation to convert seconds to days.
Video
https://user-images.githubusercontent.com/20871783/183325512-31afc495-9cc0-4883-b083-7d676bfbfdc8.mov
=> feat: add a calculation to convert seconds to days

src/components/DateCalendar.vue, src/components/Selector.vue, src/hooks/useProcessor.ts, src/views/dashboard/List.vue, src/views/dashboard/configuration/widget/AssociateOptions.vue, src/views/dashboard/controls/Tab.vue, src/views/dashboard/panel/Layout.vue, src/views/dashboard/panel/Tool.vue
Fixes picking calendar with a wrong time range and setting a unique value for dashboard grid key.
Videos
https://user-images.githubusercontent.com/20871783/185343671-27ce54af-6114-44b0-b8b1-6fd8cef2bafd.mov
https://user-images.githubusercontent.com/20871783/185343682-bf3c0bea-cdd1-4777-a237-814abf06cce3.mov
=> fix: pick calendar with a wrong time range and set a unique value for dashboard grid key

src/constants/data.ts, src/locales/lang/en.ts, src/locales/lang/es.ts, src/locales/lang/zh.ts, src/router/database.ts, src/views/dashboard/related/components/TaskDetails.vue
According to https://github.com/apache/skywalking/pull/9495#discussion_r951057489, add PostgreSQL to Database sub-menu.
Screenshot
=> feat: add PostgreSQL to Database sub-menu 

src/hooks/useProcessor.ts, src/views/dashboard/graphs/ServiceList.vue, src/views/dashboard/related/network-profiling/components/Graph/linkProcess.ts, src/views/dashboard/related/network-profiling/components/ProcessTopology.vue, src/views/dashboard/related/network-profiling/components/Tasks.vue
Fixes process widget and query process metrics
Screenshots
=> fix: update process widget and query process metrics

src/hooks/data.ts, src/hooks/useProcessor.ts, src/views/dashboard/data.ts
Add a calculation to convert nanoseconds to milliseconds.
Video 
https://user-images.githubusercontent.com/20871783/186853562-76464e0d-5406-4250-b367-9b3662540e8f.mov
=> feat: add a calculation to convert nanoseconds to milliseconds

src/views/dashboard/configuration/widget/AssociateOptions.vue
Fixes widget names.
Screenshot
=> fix: set widget name

src/views/dashboard/configuration/widget/AssociateOptions.vue, src/views/dashboard/controls/NetworkProfiling.vue, src/views/dashboard/related/network-profiling/Content.vue, src/views/dashboard/related/network-profiling/components/Settings.vue
Fixes configurations for process topology.
Video 
https://user-images.githubusercontent.com/20871783/187167239-5a278013-c9d2-4e9a-adcf-6a19a5131414.mov
=> fix: set configurations for process topology

src/views/dashboard/controls/Tab.vue
=> fix: tab active incorrectly, when click tab space

src/locales/lang/en.ts, src/locales/lang/es.ts, src/locales/lang/zh.ts, src/views/dashboard/graphs/EndpointList.vue, src/views/dashboard/graphs/InstanceList.vue, src/views/dashboard/graphs/ServiceList.vue, src/views/dashboard/graphs/style.scss
Polish the endpoint list graph.
Screenshot
=> fix: polish the endpoint list graph

src/App.vue, src/layout/components/SideBar.vue, src/views/dashboard/List.vue
Fixes styles for an adaptive height.
Screenshot
=> fix: update styles for an adaptive height

src/constants/data.ts, src/locales/lang/en.ts, src/locales/lang/es.ts, src/locales/lang/zh.ts, src/router/general.ts
Related issue https://github.com/apache/skywalking/issues/9556 。
=> Add virtual cache dashboard

src/router/general.ts, src/store/modules/profile.ts
Closes https://github.com/apache/skywalking/issues/9633
Screenshot
=> fix: remove All from the endpoints selector

src/router/data/infrastructure.ts
=> Remove commented codes

src/types/components.d.ts, src/views/dashboard/related/log/Header.vue
Closes https://github.com/apache/skywalking/issues/9716
Video 
https://user-images.githubusercontent.com/20871783/193175749-e650e7ca-d21c-46c8-82ec-d251d2dfbd41.mov
=> fix: query logs with the specific service ID

src/locales/lang/en.ts, src/locales/lang/es.ts, src/locales/lang/zh.ts, src/router/data/gateway.ts, src/types/components.d.ts, src/views/dashboard/related/trace/components/D3Graph/Index.vue, src/views/dashboard/related/trace/components/D3Graph/SpanDetail.vue, src/views/dashboard/related/trace/utils/d3-trace-list.ts
Revert logs on trace widget.
Video 
https://user-images.githubusercontent.com/20871783/195754753-49fe542f-712d-404f-8ab2-d3ee3855ff7d.mov
=> refactor: revert logs on trace widget

src/locales/lang/en.ts, src/locales/lang/es.ts, src/locales/lang/zh.ts, src/router/data/general.ts
Related  issue  https://github.com/apache/skywalking/issues/9676
=> add menu for virtual mq

src/components/Selector.vue, src/views/dashboard/configuration/Widget.vue, src/views/dashboard/configuration/widget/AssociateOptions.vue, src/views/dashboard/configuration/widget/RelatedTraceOptions.vue
Fixes https://github.com/apache/skywalking/issues/9777
Video 
https://user-images.githubusercontent.com/20871783/197722161-de1c01b5-5626-4d6f-b2e9-1be60f6d6e8a.mov
=> fix: set selector props and update configuration panel styles

src/views/dashboard/related/trace/Detail.vue
Close https://github.com/apache/skywalking/issues/9848
=> fix: remove a un-use icon

src/hooks/useListConfig.ts, src/hooks/useProcessor.ts, src/types/dashboard.d.ts, src/views/dashboard/configuration/widget/metric/Index.vue, src/views/dashboard/configuration/widget/metric/Standard.vue, src/views/dashboard/controls/Widget.vue, src/views/dashboard/graphs/EndpointList.vue, src/views/dashboard/graphs/InstanceList.vue, src/views/dashboard/graphs/Line.vue, src/views/dashboard/graphs/ServiceList.vue, src/views/dashboard/graphs/components/ColumnGraph.vue
Closes https://github.com/apache/skywalking/issues/9776
Video 
https://user-images.githubusercontent.com/20871783/198868086-ea4f2324-20dc-4c31-9684-6af02a4c3e78.mov
=> feat: support labeled value on the service/instance/endpoint list widgets

src/views/components/ConditionTags.vue, src/views/dashboard/related/trace/Filter.vue
Fixes tag keys list and duration condition.
Video / Screenshots
https://user-images.githubusercontent.com/20871783/198923027-7dfb86ca-bd47-4598-85fc-7e6a6701c0e4.mov
=> fix: reset tag keys list and duration condition

src/views/dashboard/related/profile/components/SpanTree.vue
Fixes https://github.com/apache/skywalking/discussions/9906
Video 
https://user-images.githubusercontent.com/20871783/199971235-b85df5b1-27bd-449f-9f89-8001e76a5bf2.mov
=> fix: update conditions for trace profiling

src/views/dashboard/related/topology/components/Graph.vue
=> feat: solve the problem of floating loading

src/views/components/ConditionTags.vue
Closes https://github.com/apache/skywalking/issues/9974
Video 
https://user-images.githubusercontent.com/20871783/202412008-46b63b51-96ac-4725-b573-8460758f6bc5.mov
=> feat: enhance tags component to search tags with the input value

src/views/dashboard/related/trace/utils/trace-table.ts
Fixes https://github.com/apache/skywalking/discussions/9985
Screenshot
=> fix: update condition logic for trace tree data

src/locales/lang/en.ts, src/locales/lang/es.ts, src/locales/lang/zh.ts, src/views/dashboard/configuration/widget/RelatedTraceOptions.vue, src/views/dashboard/related/trace/Header.vue
Optimize metrics related trace.
Video 
https://user-images.githubusercontent.com/20871783/202975863-53aefef8-1f78-4356-bbe9-cbd371ebacb2.mov
=> fix: optimize metrics related trace

src/components/Graph.vue, src/views/dashboard/related/trace/Header.vue
Fixes query conditions for metrics related traces.
https://user-images.githubusercontent.com/20871783/203337185-3a4c3852-8aa7-47ee-8936-5683ff1c8c6f.mov
=> fix: update query conditions for metrics related traces

src/views/dashboard/configuration/Widget.vue, src/views/dashboard/configuration/widget/RelatedTraceOptions.vue, src/views/dashboard/data.ts, src/views/dashboard/graphs/TopList.vue, src/views/dashboard/related/trace/Header.vue, src/views/dashboard/related/trace/components/D3Graph/SpanDetail.vue
Enhance associating metrics with traces by `refId`.
Video 
https://user-images.githubusercontent.com/20871783/203776288-7c47275a-c94a-4a50-bf20-f4f8a59eb489.mov
=> feat: enhance associating metrics with traces by `refId`

src/components/Radio.vue, src/components/Selector.vue, src/locales/lang/en.ts, src/locales/lang/es.ts, src/locales/lang/zh.ts, src/store/modules/network-profiling.ts, src/types/ebpf.d.ts, src/views/dashboard/related/network-profiling/components/NewConditions.vue, src/views/dashboard/related/network-profiling/components/NewTask.vue, src/views/dashboard/related/network-profiling/components/Tasks.vue, src/views/dashboard/related/network-profiling/components/data.ts
Implement creating tasks ui for network profiling widget.
Video 
https://user-images.githubusercontent.com/20871783/204182816-2c9f83f1-2740-4f8d-b078-c409cd044375.mov
=> feat: Implement creating tasks ui for network profiling widget

src/components/Graph.vue, src/styles/reset.scss, src/views/dashboard/configuration/widget/RelatedTraceOptions.vue, src/views/dashboard/controls/Widget.vue, src/views/dashboard/graphs/Area.vue, src/views/dashboard/graphs/Bar.vue, src/views/dashboard/graphs/Line.vue, src/views/dashboard/graphs/TopList.vue, src/views/dashboard/related/trace/Header.vue
Fixes metrics association.
videos / screenshots
https://user-images.githubusercontent.com/20871783/204487857-f97a4fcd-8404-4562-be3f-70428480210e.mov
https://user-images.githubusercontent.com/20871783/204487893-b3e7b7d1-00de-4db2-9c2f-e54b993650c6.mov
=> fix: optimize metrics association

src/store/modules/network-profiling.ts, src/views/dashboard/related/network-profiling/components/Tasks.vue, src/views/dashboard/related/trace/components/D3Graph/SpanDetail.vue
Fixes attached event details.
Screenshot
=> fix: update attached event details

src/views/dashboard/related/trace/components/D3Graph/SpanDetail.vue
Fixes attached event‘s occurrence date.
Screenshot
Signed-off-by: Qiuxia <qiuxiafan@apache.org>
=> fix: update attached event‘s occurrence date

src/views/dashboard/related/trace/components/D3Graph/SpanDetail.vue
Fixes attached event's details.
Screenshot
Signed-off-by:Qiuxia Fan <qiuxia@apache.org>
=> fix: update attached event's details

src/locales/lang/en.ts, src/locales/lang/es.ts, src/locales/lang/zh.ts, src/router/data/aws.ts
Relation issue: https://github.com/apache/skywalking/issues/9883
There are two things need to confirm :
1.  I didn't find an appropriate icon. 
Could we use official icon? If we could do this, I think the style of official icon is different with our UI
3. Is the order of the menu appropriate?
=> Add AWS menu for supporting AWS monitoring

vite.config.ts
=> fiix: update build config

src/assets/icons/add_iframe.svg, src/locales/lang/en.ts, src/locales/lang/es.ts, src/locales/lang/zh.ts, src/store/data.ts, src/store/modules/dashboard.ts, src/types/components.d.ts, src/views/dashboard/configuration/ThirdPartyApp.vue, src/views/dashboard/configuration/index.ts, src/views/dashboard/controls/ThirdPartyApp.vue, src/views/dashboard/controls/index.ts, src/views/dashboard/controls/tab.ts, src/views/dashboard/data.ts, src/views/dashboard/panel/Tool.vue, vite.config.ts
Closes https://github.com/apache/skywalking/issues/10000
Video 
https://user-images.githubusercontent.com/20871783/210319167-3aff7494-eba3-4147-8681-e6ea237dda5d.mov
=> feat: add a iframe widget for zipkin ui

src/components/Graph.vue, src/views/dashboard/graphs/Bar.vue, src/views/dashboard/graphs/Line.vue
Closes https://github.com/apache/skywalking/issues/10206
Video
https://user-images.githubusercontent.com/20871783/210728677-fc2fa389-1a4e-4a5d-8154-3a43dad1d196.mov
=> refactor: optimize graph tooltips to make them more friendly

src/locales/lang/en.ts, src/locales/lang/es.ts, src/locales/lang/zh.ts, src/router/data/functions.ts
Update menus for OpenFunction.
Screenshot
=> feat: update menus for OpenFunction

src/views/dashboard/related/log/Header.vue, src/views/dashboard/related/trace/Filter.vue
Fixes https://github.com/apache/skywalking/issues/10354
Video 
https://user-images.githubusercontent.com/20871783/217425397-ad163400-bc72-40b4-8e75-6d6ac076f5a8.mov
=> fix: reset duration for query conditions after time range changes

src/locales/lang/en.ts, src/locales/lang/es.ts, src/locales/lang/zh.ts, src/router/data/aws.ts
Related issue https://github.com/apache/skywalking/issues/9883
=> Add AWS S3 menu

src/store/modules/dashboard.ts
Remove duplicate query message.
Video 
https://user-images.githubusercontent.com/20871783/218096929-bfd4026e-fda7-4c70-be34-42924e9fd12f.mov
=> fix: remove duplicate query message

src/locales/lang/en.ts, src/locales/lang/es.ts, src/locales/lang/zh.ts, src/views/dashboard/Widget.vue, src/views/dashboard/components/WidgetLink.vue
Add auto period to independent mode for widgets.
Video 
https://user-images.githubusercontent.com/20871783/218933850-a079fa9f-2888-47de-b1a6-c45d9f4d9af4.mov
=> fix: add auto period to independent mode for widgets

src/layout/components/SideBar.vue, src/locales/lang/en.ts, src/locales/lang/es.ts, src/locales/lang/zh.ts, src/router/data/infrastructure.ts, src/styles/reset.scss
Closes https://github.com/apache/skywalking/issues/10398
Video 
https://user-images.githubusercontent.com/20871783/219556752-015724ca-ae0f-4b95-b9bf-cb5f146c0b46.mov
=> feat: optimize menus and add Windows monitoring menu

src/views/dashboard/related/ebpf/components/EBPFStack.vue
Fixes data processing error in the eBPF profiling widget.
Screenshot
Signed-off-by:  Qiuxia Fan <qiuxiafan@apache.org>
=> fix: data processing error in the eBPF profiling widget

src/views/dashboard/related/topology/components/Graph.vue, src/views/dashboard/related/topology/components/utils/nodeElement.ts
Fixes https://github.com/apache/skywalking/issues/10457
Video 
https://user-images.githubusercontent.com/20871783/221794623-041eae59-8b25-415e-940d-307ac9d62cf1.mov
=> fix: the wrong position of the menu when clicking the topology node

src/views/dashboard/related/topology/components/Graph.vue
Fixes alerting link in the topology widget.
Video 
https://user-images.githubusercontent.com/20871783/225566810-64c8580e-cd9b-472b-a477-0a5dca8d5ac3.mov
=> fix: update alerting link in the topology widget

src/locales/lang/en.ts, src/locales/lang/es.ts, src/locales/lang/zh.ts, src/router/data/aws.ts, src/router/data/gateway.ts
Related issue https://github.com/apache/skywalking/issues/9883
=> Add AWS API Gateway menu

src/views/dashboard/related/trace/components/Table/TableItem.vue, src/views/dashboard/related/trace/utils/d3-trace-list.ts
Polishes tooltips for trace profiling widget.
Video
https://user-images.githubusercontent.com/20871783/229353702-6897ca06-20dd-4f71-bf42-92906a67398c.mov
=> fix: polish tooltips for trace profiling widget

src/locales/lang/en.ts, src/locales/lang/es.ts, src/locales/lang/zh.ts, src/router/data/database.ts
=> Add elasticsearch menu

src/views/dashboard/graphs/Line.vue
Video 
https://user-images.githubusercontent.com/20871783/231989740-6d343889-bb63-4b7d-870d-45cbe1769372.mov
=> feat: update options for line graph

package-lock.json, package.json, src/views/dashboard/graphs/Card.vue, src/views/dashboard/graphs/EndpointList.vue, src/views/dashboard/graphs/InstanceList.vue, src/views/dashboard/graphs/ServiceList.vue, src/views/dashboard/graphs/style.scss, src/views/dashboard/panel/Tool.vue
Bump element-plus from 2.0.2 to 2.1.0, meanwhile change component styles. Fixes https://github.com/apache/skywalking-booster-ui/security/dependabot/53
=> build(deps): bump element-plus from 2.0.2 to 2.1.0 

src/views/dashboard/panel/Tool.vue
Fixes endpoint and instance selectors with url parameters.
video 
https://user-images.githubusercontent.com/20871783/235704561-4a413be8-07cb-4e16-b4c6-03ed0a2b3d32.mov
=> fix: set endpoint and instance selectors with url parameters

src/views/dashboard/graphs/EndpointList.vue, src/views/dashboard/graphs/InstanceList.vue
When the `Instance List` and `Endpoint List` graph on the same page, the `Instance List` data display error.
Video
https://github.com/apache/skywalking-booster-ui/assets/20871783/87efb114-ee5c-4354-ab95-5fdbf353de7e
=> fix: the `Instance List` data display error

package-lock.json, package.json
Reverts apache/skywalking-booster-ui#271
=> Revert "build(deps-dev): bump vite from 4.0.0 to 4.0.5"

src/hooks/useExpressionsProcessor.ts, src/hooks/useListConfig.ts, src/types/app.d.ts, src/types/dashboard.d.ts, src/views/dashboard/configuration/widget/metric/Index.vue, src/views/dashboard/configuration/widget/metric/Standard.vue, src/views/dashboard/graphs/EndpointList.vue, src/views/dashboard/graphs/InstanceList.vue, src/views/dashboard/graphs/ServiceList.vue, src/views/dashboard/graphs/components/ColumnGraph.vue
Remove metric name from queries.
Screenshots
=> feat: remove metric name from queries

src/hooks/data.ts, src/types/components.d.ts
Screenshot
asigned-off-by： Qiuxia Fan <qiuxiafan@apache.org>
=> fix: remove name filed from expression graphql

src/graphql/fragments/dashboard.ts, src/graphql/query/dashboard.ts, src/hooks/useExpressionsProcessor.ts, src/locales/lang/en.ts, src/locales/lang/es.ts, src/locales/lang/zh.ts, src/types/dashboard.d.ts, src/views/dashboard/Widget.vue, src/views/dashboard/configuration/Widget.vue, src/views/dashboard/configuration/widget/metric/Index.vue, src/views/dashboard/configuration/widget/metric/Standard.vue, src/views/dashboard/controls/Widget.vue, src/views/dashboard/graphs/EndpointList.vue, src/views/dashboard/graphs/InstanceList.vue, src/views/dashboard/graphs/ServiceList.vue, src/views/dashboard/graphs/components/ColumnGraph.vue
=> feat: remove `returnTypeOfMQE` and add detail label

src/store/modules/continous-profiling.ts, src/types/components.d.ts, src/views/dashboard/controls/Tab.vue, src/views/dashboard/related/continuous-profiling/components/InstanceList.vue, src/views/dashboard/related/continuous-profiling/components/PolicyList.vue, src/views/dashboard/related/task-timeline/Content.vue
Video 
https://github.com/apache/skywalking-booster-ui/assets/20871783/f8331c94-aec0-43a9-9962-21ce8b64d5e5
=> fix: bugs fix and polish components for continue profiling

src/graphql/fragments/ebpf.ts, src/store/modules/continous-profiling.ts, src/store/modules/task-timeline.ts, src/types/components.d.ts, src/views/dashboard/related/continuous-profiling/components/Policy.vue, src/views/dashboard/related/task-timeline/components/ProfilingPanel.vue, src/views/dashboard/related/task-timeline/components/Timeline.vue
=> feat: filter tasks with current process ID

src/hooks/useExpressionsProcessor.ts, src/views/dashboard/controls/Widget.vue
=> fix: query process metrics

src/hooks/data.ts, src/views/dashboard/Widget.vue, src/views/dashboard/controls/Widget.vue, src/views/dashboard/graphs/TopList.vue, src/views/dashboard/panel/Tool.vue
Videos
https://github.com/apache/skywalking-booster-ui/assets/20871783/e2b851dd-6f36-4f6b-a356-505ffa54b226
https://github.com/apache/skywalking-booster-ui/assets/20871783/5f9dbb38-d145-481d-ab4d-bd7defca44f4
=> fix: view related trace

src/types/components.d.ts, src/views/dashboard/controls/Tab.vue
=> fix: calculate string width to set Tabs name width

src/locales/lang/en.ts, src/views/dashboard/related/continuous-profiling/components/Policy.vue
Fixes the title of instance list and notices in the continue profiling.
=> fix: update the title of instance list and notices in the continue profiling

src/layout/components/SideBar.vue, src/router/alarm.ts, src/router/dashboard.ts, src/router/index.ts, src/router/layer.ts, src/router/marketplace.ts, src/router/settings.ts, src/store/modules/app.ts, src/views/marketplace/Menus.vue
Video 
https://github.com/apache/skywalking-booster-ui/assets/20871783/f7d577c4-8ec0-481d-8af1-32f6283df83c
=> feat: enhance the marketplace page

src/hooks/useExpressionsProcessor.ts, src/views/dashboard/graphs/Table.vue
=> fix: set chart label

.husky/commit-msg, .husky/pre-commit
resolves https://github.com/apache/skywalking/issues/11153
=> fix: commit error on Windows

src/views/dashboard/panel/Tool.vue
Video 
https://github.com/apache/skywalking-booster-ui/assets/20871783/e70a5a43-24d4-41e1-be3e-4a74c20f3735
=> fix: service associates instances

src/store/modules/event.ts
Fix https://github.com/apache/skywalking/issues/11190
=> fix: getEndpoints keyword blank

src/layout/components/NavBar.vue, src/styles/reset.scss, src/views/Marketplace.vue
Video 
https://github.com/apache/skywalking-booster-ui/assets/20871783/1a079f86-7db7-485d-9c4e-98c1c3663bc7
=> fix: update Marketplace title and breadcrumb component style

src/graphql/fragments/selector.ts, src/types/selector.d.ts, src/views/dashboard/graphs/ServiceList.vue
=> feat: add `shortName` to service list

.github/workflows/nodejs.yml, src/locales/lang/en.ts, src/locales/lang/es.ts, src/locales/lang/zh.ts, src/views/dashboard/related/trace/TraceList.vue
=> feat: add a title and a description for trace segments

src/locales/lang/en.ts, src/locales/lang/es.ts, src/locales/lang/zh.ts, src/views/dashboard/related/log/LogTable/Index.vue, src/views/dashboard/related/log/LogTable/LogDetail.vue, src/views/dashboard/related/log/LogTable/LogService.vue, src/views/dashboard/related/log/LogTable/data.ts
Video 
https://github.com/apache/skywalking-booster-ui/assets/20871783/b4ef21c6-4391-4d5e-a44b-03c0cb4808e2
Singed-off-by: Qiuxia Fan <qiuxiafan@apache.org>
=> refactor: update Logs view

src/styles/theme.scss, src/views/dashboard/related/log/LogTable/Index.vue, src/views/dashboard/related/log/LogTable/LogDetail.vue, src/views/dashboard/related/log/LogTable/LogService.vue, src/views/dashboard/related/log/LogTable/data.ts, src/views/dashboard/related/trace/components/Table/TableItem.vue
=> refactor: enhance the Log widget

src/styles/theme.scss, src/views/dashboard/related/log/LogTable/LogDetail.vue, src/views/dashboard/related/log/LogTable/LogService.vue
Video 
https://github.com/apache/skywalking-booster-ui/assets/20871783/d5523de7-cd04-4113-8458-2954d10ba569
=> fix: change log widget and loading mask style

src/views/dashboard/graphs/style.scss
Video 
https://github.com/apache/skywalking-booster-ui/assets/20871783/db02882f-6ec4-41e5-ba84-4113d65b2836
=> fix: polish list style 

src/layout/components/NavBar.vue
=> feat: support to save and load theme setting from localStorage

src/views/dashboard/related/log/LogTable/LogService.vue, src/views/dashboard/related/trace/Filter.vue
Fixes https://github.com/apache/skywalking/discussions/9371
=> fix: the service parameter is wrong when the view dump from Log to Trace widget by clicking traceID

src/hooks/useExpressionsProcessor.ts, src/router/layer.ts, src/views/dashboard/related/topology/components/Graph.vue, src/views/dashboard/related/topology/components/Metrics.vue, src/views/dashboard/related/topology/components/Settings.vue
Videos
https://github.com/apache/skywalking-booster-ui/assets/20871783/923e14db-56c1-4407-b34e-96db85c721ec
https://github.com/apache/skywalking-booster-ui/assets/20871783/6a99cd84-88d7-466f-8aee-789a2d1460d8
=> fix: change metrics config, fix tab routes

src/locales/lang/en.ts, src/locales/lang/es.ts, src/locales/lang/menus/en.ts, src/locales/lang/menus/es.ts, src/locales/lang/menus/zh.ts, src/locales/lang/zh.ts
Remove the description of OpenFunction in the UI.
=> Remove the description of OpenFunction in the UI.

src/views/dashboard/controls/Trace.vue, src/views/dashboard/related/log/Header.vue, src/views/dashboard/related/trace/Detail.vue, src/views/dashboard/related/trace/Filter.vue
Fixes https://github.com/apache/skywalking/issues/11621
Video 
https://github.com/apache/skywalking-booster-ui/assets/20871783/8773ade3-1431-4dcc-ac3e-2e5b3844065d
=> fix: Trace associates with Log widget

src/views/dashboard/related/log/LogTable/LogService.vue, src/views/dashboard/related/trace/components/D3Graph/SpanDetail.vue
Fixes https://github.com/apache/skywalking/issues/11630
Video 
https://github.com/apache/skywalking-booster-ui/assets/20871783/75cdfee7-2de9-4052-b268-b6cd52294e6e
=> fix: layout on the Log widget

src/layout/components/NavBar.vue, src/styles/theme.scss, src/types/global.d.ts
Add theme change animation
Screenshot gif:
> Use [View Transitions API](https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API), Browser support:
=> perf(Theme): add theme change animation

src/components/Tags.vue, src/locales/lang/en.ts, src/locales/lang/es.ts, src/locales/lang/zh.ts, src/types/dashboard.d.ts, src/views/dashboard/List.vue
Video
https://github.com/apache/skywalking-booster-ui/assets/20871783/f67d4e9e-3087-4fd9-9b1d-ee61fa80fce5
=> feat: add `expressions` to dashboard configurations on the dashboard list page

src/types/topology.d.ts, src/views/dashboard/related/topology/pod/InstanceMap.vue, src/views/dashboard/related/topology/service/HierarchyMap.vue
Fixes the wrong links for hierarchy topology nodes.
=> fix: link addresses on hierarchy topology nodes

src/locales/lang/en.ts, src/locales/lang/es.ts, src/locales/lang/zh.ts, src/views/dashboard/List.vue, src/views/dashboard/related/topology/pod/InstanceMap.vue, src/views/dashboard/related/topology/service/HierarchyMap.vue
Video
https://github.com/apache/skywalking-booster-ui/assets/20871783/2b0f62d6-c984-47c5-a8be-e25287416850
=> fix: polish the hierarchy topology and dashboard configs

src/store/modules/dashboard.ts, src/views/dashboard/List.vue, src/views/dashboard/related/topology/config/Metrics.vue
Video
https://github.com/apache/skywalking-booster-ui/assets/20871783/d8afab3e-d5a8-499a-aa35-f963b69a23c8
=> fix: import dashboard templates

src/store/modules/dashboard.ts
Videos
https://github.com/apache/skywalking-booster-ui/assets/20871783/9b5bf435-6e98-4492-9331-5e26521daf32
https://github.com/apache/skywalking-booster-ui/assets/20871783/f6bc34f3-7185-4420-9cbe-f649842157e7
=> fix: process dashboard templates for the new config

src/views/dashboard/panel/Tool.vue, src/views/dashboard/related/topology/components/Graph.vue, src/views/dashboard/related/topology/pod/InstanceMap.vue, src/views/dashboard/related/topology/service/HierarchyMap.vue, src/views/dashboard/related/topology/service/ServiceMap.vue, src/views/dashboard/related/topology/style.scss
=> fix: optimize tooltips style

src/graphql/fragments/topology.ts, src/store/modules/topology.ts, src/types/topology.d.ts, src/views/dashboard/related/topology/service/ServiceMap.vue
Reference https://github.com/apache/skywalking/issues/11804
Video
https://github.com/apache/skywalking-booster-ui/assets/20871783/218aa537-c26d-4c6e-b9e5-8a15b947bf61
https://github.com/apache/skywalking-booster-ui/assets/20871783/bd1b5e5c-3af5-4eb6-9196-41dd6a732409
=> feat: add the `layers` filed and associate layers dashboards for the service topology nodes

src/hooks/useExpressionsProcessor.ts
=> fix:  end loading without query results

src/components/DateCalendar.vue, src/components/TimePicker.vue, src/views/dashboard/related/topology/service/ServiceMap.vue
Video
https://github.com/apache/skywalking-booster-ui/assets/20871783/edc79166-004d-48fb-9e92-39975e576050
=> Fix: refresh nodes/calls metrics as global duration changes for Topology widget, change date picker theme

src/assets/icons/workflow_scheduler.svg, src/locales/lang/menus/en.ts, src/locales/lang/menus/es.ts, src/locales/lang/menus/zh.ts
=> Add Airflow monitor

src/hooks/useExpressionsProcessor.ts, src/views/dashboard/graphs/Table.vue
Video
https://github.com/apache/skywalking-booster-ui/assets/20871783/016b2ef5-af7c-4989-adca-9132538a55f1
=> feat: support the `SINGLE_VALUE` for table widgets

src/hooks/useExpressionsProcessor.ts
Related https://github.com/apache/skywalking/pull/12109#discussion_r1566659706
Screenshot
=> Fix the Table widget

src/components/Graph.vue, src/views/dashboard/graphs/Table.vue, src/views/dashboard/related/topology/pod/InstanceMap.vue, src/views/dashboard/related/topology/service/HierarchyMap.vue, src/views/dashboard/related/topology/service/ServiceMap.vue
=> fix: polish views without data

src/views/dashboard/controls/Trace.vue, src/views/dashboard/related/demand-log/Content.vue, src/views/dashboard/related/trace/TraceList.vue, src/views/dashboard/related/trace/components/D3Graph/Index.vue
Video
https://github.com/apache/skywalking-booster-ui/assets/66550292/e816b67a-00e3-46d1-b7de-cdc0baff13cf
Signed-off-by: Zixin Zhou [codeprince2020@163.com](mailto:codeprince2020@163.com)
=> fix: css details

src/views/dashboard/Widget.vue
Related to https://github.com/apache/skywalking/discussions/12209
Video
https://github.com/apache/skywalking-booster-ui/assets/20871783/6bb17f1b-1e01-44e9-bc16-5a0a85b3a2ed
=> Fix the widget title and tips

src/views/dashboard/related/trace/components/Statistics.vue
Before
Fixed
Signed-off-by: Zixin Zhou [zhouzixin@apache.org](mailto:zhouzixin@apache.org)
=> Fix statistics span data

src/views/dashboard/related/log/LogTable/Index.vue, src/views/dashboard/related/log/LogTable/LogBrowser.vue, src/views/dashboard/related/log/LogTable/LogDetail.vue
Video
- Fix display error in browser log
- Remove highlight after click log
https://github.com/apache/skywalking-booster-ui/assets/66550292/0efcae67-915a-4728-8993-8e097bc3f739
Signed-off-by: Zixin Zhou [zhouzixin@apache.org](mailto:zhouzixin@apache.org)
=> Fix browser log display

src/locales/lang/menus/en.ts, src/locales/lang/menus/es.ts, src/views/dashboard/related/trace/utils/d3-trace-list.ts
Close https://github.com/apache/skywalking/issues/12330
Screenshot 
=> feat: polish error nodes in trace widget

src/main.ts
Video
https://github.com/user-attachments/assets/e36d0a05-56fe-4756-832c-1ec1d8ff33e0
=> Add a loading view for initialization page

src/views/dashboard/panel/Tool.vue
Video
https://github.com/user-attachments/assets/65fcd470-2b07-49bc-99fc-6eb0c28ebd5a
=> Fix a bug for selectors when clicking the refresh icon

src/views/dashboard/graphs/InstanceList.vue, src/views/dashboard/graphs/ServiceList.vue
Video
https://github.com/user-attachments/assets/774b254d-3770-4a54-9ac3-1d1c5e78e6b4
=> Fix pagination for service/instance list widgets

src/graphql/fragments/alarm.ts, src/graphql/query/alarm.ts, src/store/modules/alarm.ts, src/views/alarm/Content.vue, src/views/components/ConditionTags.vue, src/views/dashboard/related/log/LogTable/LogDetail.vue, src/views/dashboard/related/trace/components/D3Graph/SpanDetail.vue
Video (screenshot)
https://github.com/user-attachments/assets/81f04e01-84c8-4fdf-b640-82434ac9aa51
=> feat: add queries for alarm tags

src/locales/lang/en.ts, src/locales/lang/es.ts, src/locales/lang/zh.ts, src/types/dashboard.d.ts, src/views/dashboard/Widget.vue, src/views/dashboard/configuration/Widget.vue, src/views/dashboard/configuration/widget/graph-styles/Card.vue, src/views/dashboard/configuration/widget/graph-styles/Table.vue, src/views/dashboard/configuration/widget/graph-styles/components/ContentDecorations.vue, src/views/dashboard/controls/Widget.vue, src/views/dashboard/graphs/Card.vue, src/views/dashboard/graphs/Table.vue
Related https://github.com/apache/skywalking/pull/12696#issuecomment-2410130675
Videos
https://github.com/user-attachments/assets/bc9f1a79-e7c4-4d64-b637-200db5865dfd
=> feat: add content decorations to Table and Card widgets

src/graphql/fragments/selector.ts
Related
https://github.com/apache/skywalking-query-protocol/commit/d5a8b092d1ebbc5fe330c1c2a06fa688050a21c9
Screenshot
=> feat: add `duration` to `findEndpoint`

src/views/dashboard/panel/Layout.vue
Fixed some missing metrics in the widgets during initialization dashboards.
Video
https://github.com/user-attachments/assets/d5824d97-0614-425f-90cb-f768e389ce34
=> Fix initialization dashboards

src/views/dashboard/configuration/widget/RelatedTraceOptions.vue, src/views/dashboard/data.ts, src/views/dashboard/graphs/TopList.vue, src/views/dashboard/related/trace/Header.vue
Implement owner option for TopList widgets in related trace options。
Video
https://github.com/user-attachments/assets/dd68cac2-ec76-4de2-baa7-652c4a15ca49
=> feat: implement owner option for TopList widgets in related trace options

src/hooks/data.ts, src/hooks/useExpressionsProcessor.ts, src/store/modules/topology.ts, src/views/dashboard/related/topology/config/Settings.vue, src/views/dashboard/related/topology/service/ServiceMap.vue
Video
https://github.com/user-attachments/assets/247daa93-dcca-4ac5-968b-fd5dce177c63
=> feat: Split topology metric query to avoid exceeding the maximum query complexity

src/views/dashboard/panel/Layout.vue
Video
https://github.com/user-attachments/assets/10f34d16-00f7-4a5e-a314-96a5cbddc746
=> Fix the metrics query errors from clicking refresh button

src/views/dashboard/related/trace/utils/d3-trace-list.ts, src/views/dashboard/related/trace/utils/d3-trace-tree.ts
Ref https://github.com/apache/skywalking/discussions/12785 II. Collapse span
https://github.com/user-attachments/assets/f45ab2d8-5ee1-480a-907c-9c845cf97eaa
=> feat: Add support collapse span

src/utils/copy.ts
Video
https://github.com/user-attachments/assets/e0797846-49f0-4e21-b4dd-38f207266514
=> Refactor copy util with Web API

src/graphql/fragments/selector.ts, src/locales/lang/en.ts, src/locales/lang/es.ts, src/locales/lang/zh.ts, src/store/data.ts, src/store/modules/event.ts, src/store/modules/log.ts, src/store/modules/profile.ts, src/store/modules/selectors.ts, src/store/modules/trace.ts, src/views/dashboard/graphs/EndpointList.vue, src/views/dashboard/graphs/style.scss
For more flexible search endpoints, add a topN selector to endpoint list. 
Video
https://github.com/user-attachments/assets/2660573c-910a-4f26-a273-15ebea1977ec
=> feat: add topN selector for endpoint list

src/views/dashboard/graphs/EndpointList.vue
Due to the endpoint list may contain over 20 pieces of data, the pagination is added here.
Screenshot
=> feat: add the pagination for endpoint list

src/types/trace.d.ts, src/views/dashboard/related/log/LogTable/Index.vue, src/views/dashboard/related/trace/components/D3Graph/Index.vue, src/views/dashboard/related/trace/components/D3Graph/SpanDetail.vue, src/views/dashboard/related/trace/components/List.vue, src/views/dashboard/related/trace/components/Table/Index.vue, src/views/dashboard/related/trace/utils/d3-trace-list.ts, src/views/dashboard/related/trace/utils/d3-trace-tree.ts
Change popup window style and mark parent node of the span.
Video
https://github.com/user-attachments/assets/9bcc2f09-23d0-4b02-bca2-2ba044102988
=> feat: enhance trace list graph

src/hooks/useExpressionsProcessor.ts
Fixes https://github.com/apache/skywalking/issues/13201
Video
https://github.com/user-attachments/assets/a25d5c1a-7069-4303-9678-e70697e19811
=> Fix: correct the same labels for metrics

src/graphql/http/url.ts, src/views/settings/components/TTL.vue
According to the environment(development, production) to change the prefix of http url.
Screenshot
=> Fix: Add the prefix for http url

src/components/Graph/Graph.vue, src/views/dashboard/related/topology/pod/PodMap.vue
=> fix: Correct endpoint topology data to avoid undefined

src/views/dashboard/related/trace/components/D3Graph/Index.vue, src/views/dashboard/related/trace/components/Table.vue
Video
https://github.com/user-attachments/assets/6923e3e0-c5e9-4239-9206-e26842e2ea51
=> fix: set current data when clicked span in table for tracing profiling widget

src/store/modules/trace.ts, src/views/dashboard/related/trace/components/List.vue, src/views/dashboard/related/trace/components/Tree.vue, src/views/dashboard/related/trace/utils/d3-trace-list.ts, src/views/dashboard/related/trace/utils/d3-trace-tree.ts
Fixes https://github.com/apache/skywalking/issues/13370
Screenshot
=> fix: correct the service list for legends in trace graphs

src/components/DateCalendar.vue, src/components/TimePicker.vue, src/components/__tests__/DateCalendar.spec.ts, src/components/__tests__/TimePicker.spec.ts, src/hooks/useExpressionsProcessor.ts, src/layout/components/NavBar.vue, src/views/dashboard/related/profile/components/NewTask.vue, stylelint.config.js
Closes https://github.com/apache/skywalking/issues/13416
Video
https://github.com/user-attachments/assets/9d08ce1a-a4cb-46a3-97a2-992dbaed10bd
=> feat: optimize the time picker component 

src/utils/color.ts, src/views/dashboard/related/trace/components/D3Graph/SpanDetail.vue
Video
https://github.com/user-attachments/assets/343223c6-57c6-4ac5-b9af-3acf4eb228a5
=> fix: correct the parameter for attachment events
