apache/skywalking-booster-ui

- src/locales/lang/en.ts
- src/locales/lang/zh.ts
- src/store/modules/dashboard.ts
- src/store/modules/topology.ts
- src/types/dashboard.ts
- src/views/dashboard/configuration/graph-styles/TopologyItem.vue
- src/views/dashboard/related/topology/components/Graph.vue
- src/views/dashboard/related/topology/components/PodTopology.vue
Set configs to control depth selector.
Screenshots
> feat: set configs to control depth selector

- src/store/modules/event.ts
- src/views/event/Header.vue
Add  an `all` option in layer selector for events.
Screenshot
> fix: update selectors for events

- src/components/SelectSingle.vue
- src/store/modules/topology.ts
Avoid invalid query for the topology metrics. Closes https://github.com/apache/skywalking/issues/8964
> fix: avoid invalid query for topology metrics

- src/locales/lang/en.ts
- src/locales/lang/zh.ts
- src/views/components/ConditionTags.vue
Add the alarm and log tag tips.
screenshots
> fix: add the alarm and log tag tips

- src/store/modules/profile.ts
- src/views/dashboard/related/components/LogTable/LogService.vue
- src/views/dashboard/related/profile/components/TaskList.vue
- src/views/dashboard/related/trace/components/D3Graph/SpanDetail.vue
- src/views/dashboard/related/trace/components/Table/TableItem.vue
Fixes the span details and task logs on the profile widget.
Screenshots
> fix: view spans details and task logs

- src/graphql/fragments/selector.ts
- src/types/selector.d.ts
Since the pr(https://github.com/apache/skywalking-query-protocol/pull/86), here needs to remove the layer filed for instance query.
> feat: remove the layer filed for instance query

- src/store/modules/demand-log.ts
- src/views/dashboard/panel/Layout.vue
- src/views/dashboard/panel/Tool.vue
- src/views/dashboard/related/ebpf/components/EBPFSchedules.vue
Fixes activate the correct tab index after renaming a Tabs name.
Video 
https://user-images.githubusercontent.com/20871783/172124240-8d62eeac-3ebf-477f-b4e3-ad69235f5597.mov
> fix: activate the correct tab index after renaming a Tabs name

- src/graphql/fragments/demand-log.ts
- src/store/modules/demand-log.ts
- src/views/dashboard/related/demand-log/Content.vue
- src/views/dashboard/related/demand-log/Header.vue
Set the duration and scroll position for on-demand logs.
Video 
https://user-images.githubusercontent.com/20871783/172373685-675df8a0-3834-4cb5-a569-702cc4f62f30.mov
> fix: set the duration and scroll position for on-demand logs

- src/views/dashboard/related/demand-log/Content.vue
- src/views/dashboard/related/demand-log/Header.vue
Disable the query button without containers on the on-demand log widget.
Video 
https://user-images.githubusercontent.com/20871783/172521049-cb5b0aac-ed05-4cd1-ac48-5fee4a7c226a.mov
> fix: disable the query button without containers on the on-demand log widget.

- src/views/dashboard/related/trace/components/D3Graph/SpanDetail.vue
> fix: SpanDetail text overlap

- src/views/dashboard/related/event/Content.vue
- src/views/dashboard/related/log/Header.vue
- src/views/dashboard/related/trace/Filter.vue
Set the value of the `step` filed for trace and log queries when the event widget associates with the trace and log widgets.
Video 
https://user-images.githubusercontent.com/20871783/181761867-5e47bc1e-21d0-4a36-a06d-80f2bb0a92d5.mov
> fix: set the value(SECOND) of the `step` filed for queries

- .github/workflows/nodejs.yml
- package-lock.json
The package.json and package-lock.json is not in sync, this patch makes them in sync and such we can perform reliable builds using `npm ci`.
```
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Missing: @types/lodash-es@4.17.6 from lock file
npm ERR! Missing: vue@2.7.10 from lock file
npm ERR! Missing: vue-template-compiler@2.7.10 from lock file
npm ERR! Missing: de-indent@1.0.2 from lock file
npm ERR! Missing: @vue/compiler-sfc@2.7.10 from lock file
npm ERR! Missing: csstype@3.1.0 from lock file
npm ERR! Invalid: lock file's @babel/parser@7.16.8 does not satisfy @babel/parser@7.19.0
npm ERR! …
```
> Keep package.json and package-lock.json in sync

- src/layout/components/NavBar.vue
Fixes setting up a new time range after clicking the refresh button. Closes https://github.com/apache/skywalking/issues/9582
Video 
https://user-images.githubusercontent.com/20871783/189145395-de9a7495-b0eb-461b-b19f-f03fe802b736.mov
> fix: set up a new time range after clicking the refresh button

- src/hooks/data.ts
- src/hooks/useProcessor.ts
- src/views/dashboard/data.ts
According to https://github.com/apache/skywalking-query-protocol/pull/100/files, add `readRecords` to metric types.
> feat: add `readRecords` to metric types

- src/views/dashboard/related/network-profiling/components/ProcessTopology.vue
Avoids being unable to drag process nodes for the first time.
Video 
https://user-images.githubusercontent.com/20871783/208623596-3e10ef44-dd41-43ef-bd1e-af03feccfaa9.mov
> fix: avoid being unable to drag process nodes for the first time

- .gitignore
In the main repository build, I can see the node is downloaded in the `/skywalking-ui/node` listed in the git
> Add node folder into ignore list.

- src/views/dashboard/related/log/LogTable/LogDetail.vue
The version before 8.8.0 is correct, and there are mistake after 8.8.0.
Expect
Actual
https://github.com/apache/skywalking-rocketbot-ui/pull/572
> fix: Formatted display of json content type

- package-lock.json
Fixes https://github.com/apache/skywalking-booster-ui/security/dependabot/16
> build: bump postcss to a non-vulnerable version

- src/layout/components/NavBar.vue
- src/layout/components/SideBar.vue
- src/router/data/aws.ts
- src/styles/lib.scss
Optimize side bar component to make it more friendly. When the mouse hovers the menu icons, the menu will not be collapsed. When the mouse leaves the side bar, the menu will be collapsed. Click the side bar, at the same time the menu will open.
Video 
https://user-images.githubusercontent.com/20871783/217774524-135e9d8e-7152-4608-a6b6-35fa7c61eaf8.mov
> refactor: optimize side bar component to make it more friendly

- src/hooks/data.ts
- src/hooks/useListConfig.ts
- src/hooks/useMetricsProcessor.ts
- src/views/dashboard/data.ts
Add calculations for the `cpm5dAvg`.
Video 
https://user-images.githubusercontent.com/20871783/221756396-4bf3acd4-4ab1-496d-9b03-0cae4651e2ee.mov
> feat: add calculations for the `cpm5dAvg`

- src/views/dashboard/related/topology/components/Graph.vue
Fixes incorrect operation menu content in the topology widget.
Videos 
Before 
https://user-images.githubusercontent.com/20871783/227090452-eaadd020-a92e-4d4c-84b5-315517701be4.mov
After
https://user-images.githubusercontent.com/20871783/227090549-ee90d58a-43dd-413a-8422-d4b899f45e9b.mov
Signed-off-by: Qiuxia Fan<qiuxiafan@apache.org>
> fix: incorrect operation menu content in the topology widget

- src/views/dashboard/graphs/TopList.vue
- src/views/dashboard/related/trace/Header.vue
Fixes filter ID when `ReadRecords` metric associates with trace.
Video
https://user-images.githubusercontent.com/20871783/227220704-8cae1861-0638-4b39-9d18-ba2090fb8499.mov
> fix: set filter ID when `ReadRecords` metric associates with trace 

- src/hooks/useMetricsProcessor.ts
- src/views/dashboard/configuration/widget/metric/Standard.vue
Since the input component changes type, we need to set topN type to Number.
Video 
https://github.com/apache/skywalking-booster-ui/assets/20871783/18e50184-ce2f-4245-9a79-5b2a3eba6bb7
> fix: set topN type to Number

- src/hooks/useExpressionsProcessor.ts
- src/views/dashboard/graphs/EndpointList.vue
- src/views/dashboard/graphs/InstanceList.vue
> fix: detail metrics don't display with expressions in instance list

- src/types/components.d.ts
- src/views/dashboard/configuration/widget/metric/Index.vue
- src/views/dashboard/related/continuous-profiling/components/Policy.vue
- src/views/dashboard/related/log/Header.vue
Video / Screenshot
https://github.com/apache/skywalking-booster-ui/assets/20871783/fe88bdcf-83b7-4003-9498-dba0ef5539e4
> fix: add a link to explain the expression metric, add units in the continue profiling widget

- src/views/dashboard/related/trace/components/Statistics.vue
Instead of setting minTime to 0, it should be initialized with a larger value, such as Infinity or a value that is guaranteed to be larger than any valid time value in the data set. This will ensure that the minTime value is correctly calculated during the process.
> init minTime to Infinity

- src/views/Marketplace.vue
When there is no translation of the name or description in UI, the description will be displayed with empty, and the name will be displayed with the `title` which is from query on marketplace page.
> fix: polish names and descriptions on the marketplace page

- package-lock.json
- package.json
Since [LibSass and Node Sass are deprecated](https://sass-lang.com/blog/libsass-is-deprecated), we'd better [migrate to Sass](https://sass-lang.com/blog/libsass-is-deprecated/#how-do-i-migrate). Sass is already in package.json, just execute `npm uninstall -D node-sass`.
Have tested with Node v18.17.0, scss files work fine for me.
Some issues about this [here](https://github.com/search?q=replace+node-sass&type=issues)
> fix: remove node-sass

- src/main.ts
- src/router/index.ts
- src/router/layer.ts
- vite.config.ts
As https://bugs.webkit.org/show_bug.cgi?id=242740, need to implement the menu routers with another solution for Safari.
Video 
https://github.com/apache/skywalking-booster-ui/assets/20871783/357a2ea4-ebad-4d00-9730-79084ece1993
> fix: cannot access uninitialized variable on Safari

- src/views/dashboard/graphs/Bar.vue
- src/views/dashboard/graphs/Line.vue
Fixes tooltip style to support multiple metrics scrolling view in a metrics graph
Video
https://github.com/apache/skywalking-booster-ui/assets/20871783/8e5b5593-73c9-4992-8868-1a991b2910f9
> fix: update tooltip style to support multiple metrics scrolling view in a metrics graph

- src/views/dashboard/related/trace/Index.vue
Video 
https://github.com/apache/skywalking-booster-ui/assets/20871783/98205eac-3e59-4c9b-9307-6c373a18ad15
Signed-0ff-by: Qiuxia Fan <qiuxiafan@apache.org>
> fix: set the height for trace widget

- src/router/alarm.ts
- src/router/dashboard.ts
- src/router/layer.ts
- src/router/marketplace.ts
- src/router/settings.ts
Too many chunks have resulted in a long loading time for resources.
Screenshots
before 
after
> refactor: reduce component chunks to improve page loading resource time

- src/router/index.ts
If all menus are not active, the marketplace is used
> feat: default route

- src/utils/debounce.ts
- src/views/dashboard/controls/Trace.vue
- src/views/dashboard/related/trace/Detail.vue
- src/views/dashboard/related/trace/TraceList.vue
- src/views/dashboard/related/trace/components/D3Graph/Index.vue
- src/views/dashboard/related/trace/utils/d3-trace-list.ts
- src/views/dashboard/related/trace/utils/d3-trace-tree.ts
Fixes https://github.com/apache/skywalking/issues/11809
Video
https://github.com/apache/skywalking-booster-ui/assets/20871783/c0854adc-a591-486e-a5fa-1fc1f6a7e919
> fix: resizing window causes the trace graph to display incorrectly

- src/views/dashboard/controls/Tab.vue
The _handleClick_ function calls the _stopPropagation_, so we'd better remove the click events after component unmounted to prevent potential problems, such as adding click events to the _window_ or _document_ elsewhere won't work correctly.
> fix: remove click event after unmounted

- README.md
The default UI address is `http://localhost:3000`.
```
VITE v4.5.2  ready in 2551 ms
➜  Local:   http://localhost:3000/
```
> fix(doc): fix the dev local port

- src/store/modules/topology.ts
- src/views/dashboard/related/topology/config/Settings.vue
- src/views/dashboard/related/topology/service/ServiceMap.vue
Video
https://github.com/apache/skywalking-booster-ui/assets/20871783/a742f2b6-9c1a-4c7a-81cc-3527b82b47fe
> fix: remove metrics for unreal nodes

- src/views/Marketplace.vue
Fix optimize search reset and format in marketplace
If reset and search, highlight the first menu.
Set width of category card to 100% to fix the right border
> fix: optimize search reset and format in marketplace

- src/views/dashboard/related/topology/components/utils/layout.ts
Video
https://github.com/apache/skywalking-booster-ui/assets/20871783/98469c8a-8ca1-4cda-b287-39241cc631fd
Signed-off-by: Qiuxia Fan <qiuxia@tetrate.io>
> Fix the topology layout for there are multiple independent network relationships

- src/locales/lang/en.ts
- src/locales/lang/es.ts
- src/store/modules/log.ts
- src/views/dashboard/related/log/Header.vue
- src/views/dashboard/related/log/LogTable/LogBrowser.vue
- src/views/dashboard/related/log/LogTable/LogService.vue
Video
https://github.com/apache/skywalking-booster-ui/assets/66550292/e3b2f798-9b6a-4f68-8bd1-e5a07bcf39c8
Signed-off-by: Zixin Zhou [zhouzixin@apache.org](mailto:zhouzixin@apache.org)
> feat: highlight search log keywords

- src/store/modules/log.ts
- src/views/dashboard/related/log/LogTable/LogService.vue
Fixes an error on displaying highlight words in logs.
Screenshot
> Fix highlight keywords in logs

- src/types/ebpf.d.ts
- src/utils/flameGraph.ts
- src/views/dashboard/related/ebpf/components/EBPFStack.vue
- src/views/dashboard/related/profile/Content.vue
- src/views/dashboard/related/profile/components/SpanTree.vue
- src/views/dashboard/related/profile/components/data.ts
Closes https://github.com/apache/skywalking/issues/12309
Signed-off-by: Zixin Zhou [zhouzixin@apache.org](mailto:zhouzixin@apache.org)
> feat: introduce flame graph to the trace profiling

- src/locales/lang/menus/en.ts
- src/locales/lang/menus/es.ts
- src/locales/lang/menus/zh.ts
Related to https://github.com/apache/skywalking/pull/12622.
Add SkyWalking Java Agent self observability menu in ui project.
> feat: add skywalking java agent self observability menu

- src/hooks/data.ts
- src/layout/components/NavBar.vue
- src/locales/lang/en.ts
- src/locales/lang/es.ts
- src/locales/lang/zh.ts
- src/types/dashboard.d.ts
- src/views/dashboard/Widget.vue
- src/views/dashboard/configuration/Widget.vue
- src/views/dashboard/configuration/widget/metric/Index.vue
- src/views/dashboard/controls/Widget.vue
- src/views/dashboard/graphs/TopList.vue
View dashboards by clicking data items in TopList widgets.
Video
https://github.com/user-attachments/assets/ff0043ae-5177-4559-97c7-002fab8fd94f
> feat: View data value related dashboards in TopList widgets

- src/views/dashboard/graphs/TopList.vue
Video
https://github.com/user-attachments/assets/49acedd8-60fa-4ea4-83d3-9da3812280d6
> fix: hide entrances to unrelated dashboards  in top list

- src/utils/file.ts
- src/views/dashboard/panel/Layout.vue
Releases an existing object URL which was previously created by calling [URL.createObjectURL()](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL_static).
> fix: releases an existing object URL 

- src/styles/theme.scss
- src/views/dashboard/related/async-profiling/components/NewTask.vue
Reset height for the events selector.
Screenshot
Signed-off-by: Qiuxiafan<qiuxiafan@apache.org>
> Fix: polish Async Profiling widget style

- src/store/modules/topology.ts
Fix the issue where when initiating a query on the endpoint topology page, if the query parameters contain the ID of the virtual endpoint User, all link information will be retrieved.
Fixes https://github.com/apache/skywalking/issues/12880
> Fixed the issue of querying irrelevant endpoint information on the endpoint topology page.

- src/store/modules/async-profiling.ts
- src/store/modules/topology.ts
- src/utils/vec2.ts
- src/utils/vec3.ts
- src/views/dashboard/related/async-profiling/components/TaskList.vue
- src/views/dashboard/related/network-profiling/components/Graph/layout.ts
- src/views/dashboard/related/profile/Content.vue
- src/views/dashboard/related/trace/TraceList.vue
- src/views/dashboard/related/trace/utils/d3-trace-list.ts
- src/views/dashboard/related/trace/utils/d3-trace-tree.ts
- tsconfig.vitest.json
> fix: set up async profiling tasks

- src/layout/components/SideBar.vue
- src/router/alarm.ts
- src/router/dashboard.ts
- src/router/settings.ts
From browser warnings, optimize the page router to fix duplicate names.
> Fix repetitive names in router

- src/views/dashboard/graphs/Bar.vue
- src/views/dashboard/graphs/Line.vue
Fixes tooltips cannot completely display metrics information. It can be reproduced in demo environment.
Video
https://github.com/user-attachments/assets/37c9f523-31ac-4482-9e2c-6950d5cd6eab
> Fix tooltips for metrics charts

- src/views/dashboard/components/WidgetLink.vue
The time range was incorrect when the link was generated
> fix: time range when generate link

- src/utils/validateAndSanitizeUrl.ts
- src/views/dashboard/configuration/ThirdPartyApp.vue
- src/views/dashboard/controls/ThirdPartyApp.vue
Adding strict URL validation and sanitization in the iframe widget to only allow http/https URLs and block dangerous protocols when viewing dashboards from the dashboard list. And displaying an error message if the URL is invalid.
> fix: verify URL when viewing dashboards from the dashboard list

- src/utils/__tests__/copy.spec.ts
- src/utils/copy.ts
Related https://github.com/apache/skywalking/discussions/13418
Video
https://github.com/user-attachments/assets/9ce692f1-d61e-4cde-81e3-9cf29f25daad
> fix: optimize appearing the wrong prompt by pop-up for the HTTP environments in copy function
